project:
  type: website
  output-dir: docs

website:
  title: "Sarah Eshafi"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Blog
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: [sandstone, _variables.scss]
    css: styles.css
    toc: true



